import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { UtilManagerService } from 'src/app/core/util/util-manager.service';

@Component({
  selector: 'app-exchange-rate',
  templateUrl: './exchange-rate.component.html',
  styleUrls: ['./exchange-rate.component.scss']
})
export class ExchangeRateComponent implements OnInit {
  
  currencyList: object;
  sortByPropString = "NAME" //default
  xml = '<CURRENCIES><LAST_UPDATE>2019-05-13</LAST_UPDATE><CURRENCY><NAME>Dollar</NAME><UNIT>1</UNIT><CURRENCYCODE>USD</CURRENCYCODE><COUNTRY>USA</COUNTRY><RATE>3.568</RATE><CHANGE>0.028</CHANGE></CURRENCY><CURRENCY><NAME>Pound</NAME><UNIT>1</UNIT><CURRENCYCODE>GBP</CURRENCYCODE><COUNTRY>Great Britain</COUNTRY> <RATE>4.6454</RATE><CHANGE>0.123</CHANGE> </CURRENCY> <CURRENCY> <NAME>Yen</NAME> <UNIT>100</UNIT> <CURRENCYCODE>JPY</CURRENCYCODE> <COUNTRY>Japan</COUNTRY> <RATE>3.2537</RATE> <CHANGE>0.185</CHANGE> </CURRENCY> <CURRENCY> <NAME>Euro</NAME> <UNIT>1</UNIT> <CURRENCYCODE>EUR</CURRENCYCODE> <COUNTRY>EMU</COUNTRY> <RATE>4.0089</RATE>  <CHANGE>0.067</CHANGE> </CURRENCY> <CURRENCY> <NAME>Dollar</NAME> <UNIT>1</UNIT> <CURRENCYCODE>AUD</CURRENCYCODE> <COUNTRY>Australia</COUNTRY> <RATE>2.4895</RATE> <CHANGE>-0.272</CHANGE> </CURRENCY> <CURRENCY>  <NAME>Dollar</NAME> <UNIT>1</UNIT>  <CURRENCYCODE>CAD</CURRENCYCODE> <COUNTRY>Canada</COUNTRY> <RATE>2.6561</RATE> <CHANGE>0.204</CHANGE>  </CURRENCY> <CURRENCY> <NAME>krone</NAME> <UNIT>1</UNIT> <CURRENCYCODE>DKK</CURRENCYCODE> <COUNTRY>Denmark</COUNTRY> <RATE>0.5369</RATE> <CHANGE>0.056</CHANGE> </CURRENCY> <CURRENCY> <NAME>Krone</NAME> <UNIT>1</UNIT>  <CURRENCYCODE>NOK</CURRENCYCODE> <COUNTRY>Norway</COUNTRY> <RATE>0.4083</RATE> <CHANGE>0.049</CHANGE> </CURRENCY> <CURRENCY> <NAME>Rand</NAME> <UNIT>1</UNIT> <CURRENCYCODE>ZAR</CURRENCYCODE> <COUNTRY>South Africa</COUNTRY> <RATE>0.2498</RATE> <CHANGE>-0.399</CHANGE> </CURRENCY> <CURRENCY> <NAME>Krona</NAME> <UNIT>1</UNIT> <CURRENCYCODE>SEK</CURRENCYCODE> <COUNTRY>Sweden</COUNTRY> <RATE>0.37</RATE> <CHANGE>-0.216</CHANGE> </CURRENCY> <CURRENCY> <NAME>Franc</NAME> <UNIT>1</UNIT> <CURRENCYCODE>CHF</CURRENCYCODE> <COUNTRY>Switzerland</COUNTRY> <RATE>3.5388</RATE> <CHANGE>0.557</CHANGE> </CURRENCY> <CURRENCY> <NAME>Dinar</NAME> <UNIT>1</UNIT> <CURRENCYCODE>JOD</CURRENCYCODE> <COUNTRY>Jordan</COUNTRY> <RATE>5.0327</RATE> <CHANGE>-0.04</CHANGE> </CURRENCY> <CURRENCY> <NAME>Pound</NAME> <UNIT>10</UNIT> <CURRENCYCODE>LBP</CURRENCYCODE> <COUNTRY>Lebanon</COUNTRY> <RATE>0.0237</RATE> <CHANGE>0.424</CHANGE> </CURRENCY> <CURRENCY> <NAME>Pound</NAME><UNIT>1</UNIT> <CURRENCYCODE>EGP</CURRENCYCODE> <COUNTRY>Egypt</COUNTRY> <RATE>0.2089</RATE> <CHANGE>0.288</CHANGE></CURRENCY></CURRENCIES>';
  
  constructor(private route: ActivatedRoute, private utilManager: UtilManagerService) { }

  ngOnInit() {
    this.initData();
  }

  initData() {
    this.currencyList = this.utilManager.convertXmlToJson(this.xml)['CURRENCIES'];
  }

  setSortByProp(propName: string) {
    this.sortByPropString = propName;
  }

}
